version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${POSTGRES_DB}
    ports:
     - '5432:5432'
    volumes: 
     - db:/var/lib/postgresql/data
     - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  server:
    build: 
      context: .
      dockerfile: server.dockerfile
    image: mzakrzwsk/server_test
    depends_on:
      - db
    ports:
    - 5000:5000
    links:
    - db
    volumes:
    - ./:/src'

volumes:
  db:
    driver: local



